In [3]:
import os
import os.path
import pandas as pd
import numpy as np
import datetime

print('job complete')

job complete

In [4]:
"""

Here we need to define the current year, and previous 2 years in order to have history
"""

Today_Date = datetime.datetime.now()
Current_Start = datetime.datetime(2022, 9, 8) ## -> this is manually set each year


if Today_Date < Current_Start:
    Year_Variable = (Current_Start.year) - 1
else:
    Year_Variable = Current_Start.year

year_prior2 = str(Year_Variable - 2)
year_prior1 = str(Year_Variable - 1)
year_current = str(Year_Variable)

print(year_current,year_prior1,year_prior2)

2022 2021 2020

In [5]:
#######################################################################################
##                                                                                   ##
##            build out a single DataFrame with 3 years of Offense                   ##
##                                                                                   ##
#######################################################################################

#######################################################################################
##                                                                                   ##
##                                Passing                                            ##
##                                                                                   ##
#######################################################################################

df_PASS_CURRENT = pd.read_html('https://www.pro-football-reference.com/years/' + year_current + '/passing.htm')
df_PASS_PRIOR_1 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior1 + '/passing.htm')
df_PASS_PRIOR_2 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior2 + '/passing.htm')

df_PASS_CURRENT = df_PASS_CURRENT[-1]
df_PASS_PRIOR_1 = df_PASS_PRIOR_1[-1]
df_PASS_PRIOR_2 = df_PASS_PRIOR_2[-1]

## Filter out bad rows of data from source
df_PASS_CURRENT = df_PASS_CURRENT[df_PASS_CURRENT['Player'] != "Player"]
df_PASS_CURRENT = df_PASS_CURRENT[df_PASS_CURRENT['G'] != "G"]

df_PASS_PRIOR_1 = df_PASS_PRIOR_1[df_PASS_PRIOR_1['Player'] != "Player"]
df_PASS_PRIOR_1 = df_PASS_PRIOR_1[df_PASS_PRIOR_1['G'] != "G"]

df_PASS_PRIOR_2 = df_PASS_PRIOR_2[df_PASS_PRIOR_2['Player'] != "Player"]
df_PASS_PRIOR_2 = df_PASS_PRIOR_2[df_PASS_PRIOR_2['G'] != "G"]

## build current year dict
DF_PASS_CURRENT_dict = {'PLAYER_NAME_SOURCE': df_PASS_CURRENT['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                'PLAYER_POSITION_SOURCE': df_PASS_CURRENT['Pos'].fillna("N"),
#                'UNIQUE_JOIN': df_PASS_CURRENT['Player'].fillna("N") + df_PASS_CURRENT['Pos'].fillna("N") + year_current,
                'FANTASY_YEAR': year_current,
                'GAMES_PLAYED': df_PASS_CURRENT['G'].astype(int).fillna(0),
                'PASSING_YDS': df_PASS_CURRENT['Yds'].astype(int).fillna(0),
                'PASSING_TD': df_PASS_CURRENT['TD'].astype(int).fillna(0),
                'PASSING_INT': df_PASS_CURRENT['Int'].astype(int).fillna(0),
                'PASSING_SACK': df_PASS_CURRENT['Sk'].astype(int).fillna(0),
                'NAME_CHECK_VAL': df_PASS_CURRENT['Player'].str[-2:].astype(str),
                'NAME_CHECK_2_VAL': df_PASS_CURRENT['Player'].str[-1:].astype(str),
                'NAME_CHECK_CALC': df_PASS_CURRENT['Player'].str[:-2].astype(str),
                'NAME_CHECK_CALC_2': df_PASS_CURRENT['Player'].str[:-1].astype(str)
               }

#convert the dictionairy to a DataFrame
df_PASS_CURRENT = pd.DataFrame(DF_PASS_CURRENT_dict)

df_PASS_CURRENT['UNIQUE_JOIN'] = df_PASS_CURRENT['PLAYER_NAME_SOURCE'] + df_PASS_CURRENT['PLAYER_POSITION_SOURCE'] + df_PASS_CURRENT['FANTASY_YEAR']

## build prior year 1 dict
DF_PASS_PRIOR_1_dict = {'PLAYER_NAME_SOURCE': df_PASS_PRIOR_1['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                'PLAYER_POSITION_SOURCE': df_PASS_PRIOR_1['Pos'].fillna("N"),
#                'UNIQUE_JOIN': df_PASS_PRIOR_1['Player'].fillna("N") + df_PASS_PRIOR_1['Pos'].fillna("N") + year_prior1,
                'FANTASY_YEAR': year_prior1,
                'GAMES_PLAYED': df_PASS_PRIOR_1['G'].astype(int).fillna(0),
                'PASSING_YDS': df_PASS_PRIOR_1['Yds'].astype(int).fillna(0),
                'PASSING_TD': df_PASS_PRIOR_1['TD'].astype(int).fillna(0),
                'PASSING_INT': df_PASS_PRIOR_1['Int'].astype(int).fillna(0),
                'PASSING_SACK': df_PASS_PRIOR_1['Sk'].astype(int).fillna(0),
                'NAME_CHECK_VAL': df_PASS_PRIOR_1['Player'].str[-2:].astype(str),
                'NAME_CHECK_2_VAL': df_PASS_PRIOR_1['Player'].str[-1:].astype(str),
                'NAME_CHECK_CALC': df_PASS_PRIOR_1['Player'].str[:-2].astype(str),
                'NAME_CHECK_CALC_2': df_PASS_PRIOR_1['Player'].str[:-1].astype(str)
               }

#convert the dictionairy to a DataFrame
df_PASS_PRIOR_1 = pd.DataFrame(DF_PASS_PRIOR_1_dict)

df_PASS_PRIOR_1['UNIQUE_JOIN'] = df_PASS_PRIOR_1['PLAYER_NAME_SOURCE'] + df_PASS_PRIOR_1['PLAYER_POSITION_SOURCE'] + df_PASS_PRIOR_1['FANTASY_YEAR']

## build prior year 2 dict
DF_PASS_PRIOR_2_dict = {'PLAYER_NAME_SOURCE': df_PASS_PRIOR_2['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                'PLAYER_POSITION_SOURCE': df_PASS_PRIOR_2['Pos'].fillna("N"),
#                'UNIQUE_JOIN': df_PASS_PRIOR_2['Player'].fillna("N") + df_PASS_PRIOR_2['Pos'].fillna("N") + year_prior2,
                'FANTASY_YEAR': year_prior2,
                'GAMES_PLAYED': df_PASS_PRIOR_2['G'].astype(int).fillna(0),
                'PASSING_YDS': df_PASS_PRIOR_2['Yds'].astype(int).fillna(0),
                'PASSING_TD': df_PASS_PRIOR_2['TD'].astype(int).fillna(0),
                'PASSING_INT': df_PASS_PRIOR_2['Int'].astype(int).fillna(0),
                'PASSING_SACK': df_PASS_PRIOR_2['Sk'].astype(int).fillna(0),
                'NAME_CHECK_VAL': df_PASS_PRIOR_2['Player'].str[-2:].astype(str),
                'NAME_CHECK_2_VAL': df_PASS_PRIOR_2['Player'].str[-1:].astype(str),
                'NAME_CHECK_CALC': df_PASS_PRIOR_2['Player'].str[:-2].astype(str),
                'NAME_CHECK_CALC_2': df_PASS_PRIOR_2['Player'].str[:-1].astype(str)
               }

#convert the dictionairy to a DataFrame
df_PASS_PRIOR_2 = pd.DataFrame(DF_PASS_PRIOR_2_dict)

df_PASS_PRIOR_2['UNIQUE_JOIN'] = df_PASS_PRIOR_2['PLAYER_NAME_SOURCE'] + df_PASS_PRIOR_2['PLAYER_POSITION_SOURCE'] + df_PASS_PRIOR_2['FANTASY_YEAR']

df_PASS_ALL = pd.concat([df_PASS_CURRENT, df_PASS_PRIOR_1,df_PASS_PRIOR_2])


#######################################################################################
##                                                                                   ##
##                                Rushing                                            ##
##                                                                                   ##
#######################################################################################

df_RUSH_CURRENT = pd.read_html('https://www.pro-football-reference.com/years/' + year_current + '/rushing.htm', header=1)
df_RUSH_PRIOR_1 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior1 + '/rushing.htm', header=1)
df_RUSH_PRIOR_2 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior2 + '/rushing.htm', header=1)

df_RUSH_CURRENT = df_RUSH_CURRENT[-1]
df_RUSH_PRIOR_1 = df_RUSH_PRIOR_1[-1]
df_RUSH_PRIOR_2 = df_RUSH_PRIOR_2[-1]

## Filter out bad rows of data from source
df_RUSH_CURRENT = df_RUSH_CURRENT[df_RUSH_CURRENT['Player'] != "Player"]
df_RUSH_CURRENT = df_RUSH_CURRENT[df_RUSH_CURRENT['G'] != "G"]

df_RUSH_PRIOR_1 = df_RUSH_PRIOR_1[df_RUSH_PRIOR_1['Player'] != "Player"]
df_RUSH_PRIOR_1 = df_RUSH_PRIOR_1[df_RUSH_PRIOR_1['G'] != "G"]

df_RUSH_PRIOR_2 = df_RUSH_PRIOR_2[df_RUSH_PRIOR_2['Player'] != "Player"]
df_RUSH_PRIOR_2 = df_RUSH_PRIOR_2[df_RUSH_PRIOR_2['G'] != "G"]

## build current year dict
df_RUSH_CURRENT_dict = {'PLAYER_NAME_SOURCE': df_RUSH_CURRENT['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                'PLAYER_POSITION_SOURCE': df_RUSH_CURRENT['Pos'].fillna("N"),
#                'UNIQUE_JOIN': df_RUSH_CURRENT['Player'].fillna("N") + df_RUSH_CURRENT['Pos'].fillna("N") + year_current,
                'FANTASY_YEAR': year_current,
                'GAMES_PLAYED': df_RUSH_CURRENT['G'].astype(int).fillna(0),
                'RUSH_YDS': df_RUSH_CURRENT['Yds'].astype(int).fillna(0),
                'RUSH_TD': df_RUSH_CURRENT['TD'].astype(int).fillna(0),
                'RUSH_FMB': df_RUSH_CURRENT['Fmb'].astype(int).fillna(0),
                'NAME_CHECK_VAL': df_RUSH_CURRENT['Player'].str[-2:].astype(str),
                'NAME_CHECK_2_VAL': df_RUSH_CURRENT['Player'].str[-1:].astype(str),
                'NAME_CHECK_CALC': df_RUSH_CURRENT['Player'].str[:-2].astype(str),
                'NAME_CHECK_CALC_2': df_RUSH_CURRENT['Player'].str[:-1].astype(str)                
               }

#convert the dictionairy to a DataFrame
df_RUSH_CURRENT = pd.DataFrame(df_RUSH_CURRENT_dict)

df_RUSH_CURRENT['UNIQUE_JOIN'] = df_RUSH_CURRENT['PLAYER_NAME_SOURCE'] + df_RUSH_CURRENT['PLAYER_POSITION_SOURCE'] + df_RUSH_CURRENT['FANTASY_YEAR']

df_RUSH_CURRENT

## build Prior 1 year dict
df_RUSH_PRIOR_1_dict = {'PLAYER_NAME_SOURCE': df_RUSH_PRIOR_1['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                'PLAYER_POSITION_SOURCE': df_RUSH_PRIOR_1['Pos'].fillna("N"),
#                'UNIQUE_JOIN': df_RUSH_PRIOR_1['Player'].fillna("N") + df_RUSH_PRIOR_1['Pos'].fillna("N") + year_prior1,
                'FANTASY_YEAR': year_prior1,
                'GAMES_PLAYED': df_RUSH_PRIOR_1['G'].astype(int).fillna(0),
                'RUSH_YDS': df_RUSH_PRIOR_1['Yds'].astype(int).fillna(0),
                'RUSH_TD': df_RUSH_PRIOR_1['TD'].astype(int).fillna(0),
                'RUSH_FMB': df_RUSH_PRIOR_1['Fmb'].astype(int).fillna(0),
                'NAME_CHECK_VAL': df_RUSH_PRIOR_1['Player'].str[-2:].astype(str),
                'NAME_CHECK_2_VAL': df_RUSH_PRIOR_1['Player'].str[-1:].astype(str),
                'NAME_CHECK_CALC': df_RUSH_PRIOR_1['Player'].str[:-2].astype(str),
                'NAME_CHECK_CALC_2': df_RUSH_PRIOR_1['Player'].str[:-1].astype(str)                
               }

#convert the dictionairy to a DataFrame
df_RUSH_PRIOR_1 = pd.DataFrame(df_RUSH_PRIOR_1_dict)

df_RUSH_PRIOR_1['UNIQUE_JOIN'] = df_RUSH_PRIOR_1['PLAYER_NAME_SOURCE'] + df_RUSH_PRIOR_1['PLAYER_POSITION_SOURCE'] + df_RUSH_PRIOR_1['FANTASY_YEAR']

## build Prior 2 year dict
df_RUSH_PRIOR_2_dict = {'PLAYER_NAME_SOURCE': df_RUSH_PRIOR_2['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                'PLAYER_POSITION_SOURCE': df_RUSH_PRIOR_2['Pos'].fillna("N"),
#                'UNIQUE_JOIN': df_RUSH_PRIOR_2['Player'].fillna("N") + df_RUSH_PRIOR_2['Pos'].fillna("N") + year_prior2,
                'FANTASY_YEAR': year_prior2,
                'GAMES_PLAYED': df_RUSH_PRIOR_2['G'].astype(int).fillna(0),
                'RUSH_YDS': df_RUSH_PRIOR_2['Yds'].astype(int).fillna(0),
                'RUSH_TD': df_RUSH_PRIOR_2['TD'].astype(int).fillna(0),
                'RUSH_FMB': df_RUSH_PRIOR_2['Fmb'].astype(int).fillna(0),
                'NAME_CHECK_VAL': df_RUSH_PRIOR_2['Player'].str[-2:].astype(str),
                'NAME_CHECK_2_VAL': df_RUSH_PRIOR_2['Player'].str[-1:].astype(str),
                'NAME_CHECK_CALC': df_RUSH_PRIOR_2['Player'].str[:-2].astype(str),
                'NAME_CHECK_CALC_2': df_RUSH_PRIOR_2['Player'].str[:-1].astype(str)                
               }

#convert the dictionairy to a DataFrame
df_RUSH_PRIOR_2 = pd.DataFrame(df_RUSH_PRIOR_2_dict)

df_RUSH_PRIOR_2['UNIQUE_JOIN'] = df_RUSH_PRIOR_2['PLAYER_NAME_SOURCE'] + df_RUSH_PRIOR_2['PLAYER_POSITION_SOURCE'] + df_RUSH_PRIOR_2['FANTASY_YEAR']

df_RUSH_ALL = pd.concat([df_RUSH_CURRENT, df_RUSH_PRIOR_1,df_RUSH_PRIOR_2])

#######################################################################################
##                                                                                   ##
##                                    Receiving                                      ##
##                                                                                   ##
#######################################################################################

df_REC_CURRENT = pd.read_html('https://www.pro-football-reference.com/years/' + year_current + '/receiving.htm')
df_REC_PRIOR_1 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior1 + '/receiving.htm')
df_REC_PRIOR_2 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior2 + '/receiving.htm')

df_REC_CURRENT = df_REC_CURRENT[-1]
df_REC_PRIOR_1 = df_REC_PRIOR_1[-1]
df_REC_PRIOR_2 = df_REC_PRIOR_2[-1]

## Filter out bad rows of data from source
df_REC_CURRENT = df_REC_CURRENT[df_REC_CURRENT['Player'] != "Player"]
df_REC_CURRENT = df_REC_CURRENT[df_REC_CURRENT['G'] != "G"]

df_REC_PRIOR_1 = df_REC_PRIOR_1[df_REC_PRIOR_1['Player'] != "Player"]
df_REC_PRIOR_1 = df_REC_PRIOR_1[df_REC_PRIOR_1['G'] != "G"]

df_REC_PRIOR_2 = df_REC_PRIOR_2[df_REC_PRIOR_2['Player'] != "Player"]
df_REC_PRIOR_2 = df_REC_PRIOR_2[df_REC_PRIOR_2['G'] != "G"]

## build Current year dict
df_REC_CURRENT_dict = {'PLAYER_NAME_SOURCE': df_REC_CURRENT['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                       'PLAYER_POSITION_SOURCE': df_REC_CURRENT['Pos'].fillna("N"),
#                       'UNIQUE_JOIN': df_REC_CURRENT['Player'].fillna("N") + df_REC_CURRENT['Pos'].fillna("N") + year_current,
                       'FANTASY_YEAR': year_current,
                       'GAMES_PLAYED': df_REC_CURRENT['G'].astype(int).fillna(0),
                       'REC_YDS': df_REC_CURRENT['Yds'].astype(int).fillna(0),
                       'REC_CATCH': df_REC_CURRENT['Rec'].astype(int).fillna(0),
                       'REC_TD': df_REC_CURRENT['TD'].astype(int).fillna(0),
                       'REC_FMBL': df_REC_CURRENT['Fmb'].astype(int).fillna(0),
                       'NAME_CHECK_VAL': df_REC_CURRENT['Player'].str[-2:].astype(str),
                       'NAME_CHECK_2_VAL': df_REC_CURRENT['Player'].str[-1:].astype(str),
                       'NAME_CHECK_CALC': df_REC_CURRENT['Player'].str[:-2].astype(str),
                       'NAME_CHECK_CALC_2': df_REC_CURRENT['Player'].str[:-1].astype(str)
                      }

#convert the dictionairy to a DataFrame
df_REC_CURRENT = pd.DataFrame(df_REC_CURRENT_dict)

df_REC_CURRENT['UNIQUE_JOIN'] = df_REC_CURRENT['PLAYER_NAME_SOURCE'] + df_REC_CURRENT['PLAYER_POSITION_SOURCE'] + df_REC_CURRENT['FANTASY_YEAR']

## build Prior 1 year dict
df_REC_PRIOR_1_dict = {'PLAYER_NAME_SOURCE': df_REC_PRIOR_1['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                       'PLAYER_POSITION_SOURCE': df_REC_PRIOR_1['Pos'].fillna("N"),
#                       'UNIQUE_JOIN': df_REC_PRIOR_1['Player'].fillna("N") + df_REC_PRIOR_1['Pos'].fillna("N") + year_prior1,
                       'FANTASY_YEAR': year_prior1,
                       'GAMES_PLAYED': df_REC_PRIOR_1['G'].astype(int).fillna(0),
                       'REC_YDS': df_REC_PRIOR_1['Yds'].astype(int).fillna(0),
                       'REC_CATCH': df_REC_PRIOR_1['Rec'].astype(int).fillna(0),
                       'REC_TD': df_REC_PRIOR_1['TD'].astype(int).fillna(0),
                       'REC_FMBL': df_REC_PRIOR_1['Fmb'].astype(int).fillna(0),
                       'NAME_CHECK_VAL': df_REC_PRIOR_1['Player'].str[-2:].astype(str),
                       'NAME_CHECK_2_VAL': df_REC_PRIOR_1['Player'].str[-1:].astype(str),
                       'NAME_CHECK_CALC': df_REC_PRIOR_1['Player'].str[:-2].astype(str),
                       'NAME_CHECK_CALC_2': df_REC_PRIOR_1['Player'].str[:-1].astype(str)
                      }

#convert the dictionairy to a DataFrame
df_REC_PRIOR_1 = pd.DataFrame(df_REC_PRIOR_1_dict)

df_REC_PRIOR_1['UNIQUE_JOIN'] = df_REC_PRIOR_1['PLAYER_NAME_SOURCE'] + df_REC_PRIOR_1['PLAYER_POSITION_SOURCE'] + df_REC_PRIOR_1['FANTASY_YEAR']

## build Prior 2 year dict
df_REC_PRIOR_2_dict = {'PLAYER_NAME_SOURCE': df_REC_PRIOR_2['Player'].fillna("N").replace('Derrick Henry *','Derrick Henry*'),
                       'PLAYER_POSITION_SOURCE': df_REC_PRIOR_2['Pos'].fillna("N"),
#                       'UNIQUE_JOIN': df_REC_PRIOR_2['Player'].fillna("N") + df_REC_PRIOR_2['Pos'].fillna("N") + year_prior2,
                       'FANTASY_YEAR': year_prior2,
                       'GAMES_PLAYED': df_REC_PRIOR_2['G'].astype(int).fillna(0),
                       'REC_YDS': df_REC_PRIOR_2['Yds'].astype(int).fillna(0),
                       'REC_CATCH': df_REC_PRIOR_2['Rec'].astype(int).fillna(0),
                       'REC_TD': df_REC_PRIOR_2['TD'].astype(int).fillna(0),
                       'REC_FMBL': df_REC_PRIOR_2['Fmb'].fillna(0).astype(int),
                       'NAME_CHECK_VAL': df_REC_PRIOR_2['Player'].str[-2:].astype(str),
                       'NAME_CHECK_2_VAL': df_REC_PRIOR_2['Player'].str[-1:].astype(str),
                       'NAME_CHECK_CALC': df_REC_PRIOR_2['Player'].str[:-2].astype(str),
                       'NAME_CHECK_CALC_2': df_REC_PRIOR_2['Player'].str[:-1].astype(str)
                      }

#convert the dictionairy to a DataFrame
df_REC_PRIOR_2 = pd.DataFrame(df_REC_PRIOR_2_dict)

df_REC_PRIOR_2['UNIQUE_JOIN'] = df_REC_PRIOR_2['PLAYER_NAME_SOURCE'] + df_REC_PRIOR_2['PLAYER_POSITION_SOURCE'] + df_REC_PRIOR_2['FANTASY_YEAR']

df_REC_ALL = pd.concat([df_REC_CURRENT, df_REC_PRIOR_1,df_REC_PRIOR_2])

#######################################################################################
##                                                                                   ##
##                                Offense                                            ##
##                                                                                   ##
#######################################################################################

df_PASS_ROSTER = df_PASS_ALL.filter(['UNIQUE_JOIN',
                                     'PLAYER_NAME_SOURCE',
                                     'PLAYER_POSITION_SOURCE',
                                     'FANTASY_YEAR',
                                     'GAMES_PLAYED',
                                     'NAME_CHECK_VAL',
                                     'NAME_CHECK_2_VAL',
                                     'NAME_CHECK_CALC',
                                     'NAME_CHECK_CALC_2'
                                    ])
#df_PASS_ROSTER['datasource'] = 'Passing'

df_RUSH_ROSTER = df_RUSH_ALL.filter(['UNIQUE_JOIN',
                                     'PLAYER_NAME_SOURCE',
                                     'PLAYER_POSITION_SOURCE',
                                     'FANTASY_YEAR',
                                     'GAMES_PLAYED',
                                     'NAME_CHECK_VAL',
                                     'NAME_CHECK_2_VAL',
                                     'NAME_CHECK_CALC',
                                     'NAME_CHECK_CALC_2'
                                    ])
#df_RUSH_ROSTER['datasource'] = 'Rush'


df_REC_ROSTER = df_REC_ALL.filter(['UNIQUE_JOIN',
                                     'PLAYER_NAME_SOURCE',
                                     'PLAYER_POSITION_SOURCE',
                                   'FANTASY_YEAR',
                                   'GAMES_PLAYED',
                                     'NAME_CHECK_VAL',
                                     'NAME_CHECK_2_VAL',
                                     'NAME_CHECK_CALC',
                                     'NAME_CHECK_CALC_2'
                                    ])
#df_REC_ROSTER['datasource'] = 'Receiving'

df_OFFENSE_ROSTER_ALL = pd.concat([df_PASS_ROSTER, df_RUSH_ROSTER,df_REC_ROSTER]).drop_duplicates()


"""
df_OFFENSE_ROSTER_ALL

df_PASS_ALL.info()
df_RUSH_ALL.info()
df_REC_ALL.info()
df_OFFENSE_ROSTER_ALL.info()

"""

#define condition of each value
conditions = [
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL'] == "+*"),
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL'] == "*+")
]

# Define result depending on the condition met
values = ["Y","Y"]

# Apply Condition -> result logic as a new column in the DataFrame
df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_TEST'] = np.select(conditions, values)

#define condition of each value
conditions = [
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_2_VAL'] == "+"),
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_2_VAL'] == "*")
]

# Define result depending on the condition met
values = ["Y","Y"]

# Apply Condition -> result logic as a new column in the DataFrame
df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_2_TEST'] = np.select(conditions, values)

df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_TEST_CONCAT'] = df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_TEST'] + df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_2_TEST']


#define condition of each value
conditions = [
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_TEST'] == "Y"),
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_2_TEST'] == "Y"),
    (df_OFFENSE_ROSTER_ALL['NAME_CHECK_VAL_TEST_CONCAT'] == "00")
]

# Define result depending on the condition met
values = [df_OFFENSE_ROSTER_ALL['NAME_CHECK_CALC'],df_OFFENSE_ROSTER_ALL['NAME_CHECK_CALC_2'],df_OFFENSE_ROSTER_ALL['PLAYER_NAME_SOURCE']]

# Apply Condition -> result logic as a new column in the DataFrame
df_OFFENSE_ROSTER_ALL['PLAYER_NAME'] = np.select(conditions, values)

# Clean up DF columns
df_OFFENSE_ROSTER_ALL = df_OFFENSE_ROSTER_ALL.filter(['UNIQUE_JOIN',
                                                      'PLAYER_NAME',
                                                      'PLAYER_POSITION_SOURCE',
                                                      'GAMES_PLAYED',
                                                      'FANTASY_YEAR'
                                                     ])

df_1 = df_PASS_ALL.filter(['UNIQUE_JOIN',
                           'PASSING_YDS',
                           'PASSING_TD',
                           'PASSING_INT',
                           'PASSING_SACK'
                          ])

df_2 = df_RUSH_ALL.filter(['UNIQUE_JOIN',
                           'RUSH_YDS',
                           'RUSH_TD',
                           'RUSH_FMB'
                          ])

df_3 = df_REC_ALL.filter(['UNIQUE_JOIN',
                           'REC_YDS',
                           'REC_TD',
                           'REC_FMBL',
                          'REC_CATCH'
                          ])

df_OFFENSE_ROSTER_ALL = pd.merge(df_OFFENSE_ROSTER_ALL,df_1, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()
df_OFFENSE_ROSTER_ALL = pd.merge(df_OFFENSE_ROSTER_ALL,df_2, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()
df_OFFENSE_ROSTER_ALL = pd.merge(df_OFFENSE_ROSTER_ALL,df_3, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

#df_OFFENSE_ROSTER_ALL = df_OFFENSE_ROSTER_ALL[df_OFFENSE_ROSTER_ALL['PLAYER_NAME'] == "Patrick Mahomes"]

#define condition of each value
conditions = [
    (df_OFFENSE_ROSTER_ALL['RUSH_FMB'] == 0),
    (df_OFFENSE_ROSTER_ALL['RUSH_FMB'] >= 1)
]

# Define result depending on the condition met
values = [df_OFFENSE_ROSTER_ALL['REC_FMBL'],df_OFFENSE_ROSTER_ALL['RUSH_FMB']]

# Apply Condition -> result logic as a new column in the DataFrame
df_OFFENSE_ROSTER_ALL['OFF_FMBL'] = np.select(conditions, values)

#define condition of each value
conditions = [
    (df_OFFENSE_ROSTER_ALL['PLAYER_POSITION_SOURCE'] == "QB"),
    (df_OFFENSE_ROSTER_ALL['PLAYER_POSITION_SOURCE'] == "WR"),
    (df_OFFENSE_ROSTER_ALL['PLAYER_POSITION_SOURCE'] == "RB"),
    (df_OFFENSE_ROSTER_ALL['PLAYER_POSITION_SOURCE'] == "FB"),
    (df_OFFENSE_ROSTER_ALL['PLAYER_POSITION_SOURCE'] == "TE")
]

# Define result depending on the condition met
values = ['QB','WR','RB','RB','TE']

# Apply Condition -> result logic as a new column in the DataFrame
df_OFFENSE_ROSTER_ALL['PLAYER_POSITION'] = np.select(conditions, values)

df_OFFENSE_ROSTER_ALL

df_OFF_KPI_ROSTER = df_OFFENSE_ROSTER_ALL.filter(['UNIQUE_JOIN',
                                                  'PLAYER_NAME',
                                                  'PLAYER_POSITION',
                                                  'GAMES_PLAYED',
                                                  'FANTASY_YEAR',
                                                  'PASSING_YDS',
                                                  'PASSING_TD',
                                                  'PASSING_INT',
                                                  'PASSING_SACK',
                                                  'RUSH_YDS',
                                                  'RUSH_TD',
                                                  'REC_YDS',
                                                  'REC_TD',
                                                  'REC_CATCH',
                                                  'OFF_FMBL',
                                                 ])


##############################################################################

# clean up the unique join for pbi consumptionto bring in 40+ yd pass/rec 
df_OFF_KPI_ROSTER['UNIQUE_JOIN'] = df_OFF_KPI_ROSTER['UNIQUE_JOIN'].str.replace('*','', regex=True)
df_OFF_KPI_ROSTER['UNIQUE_JOIN'] = df_OFF_KPI_ROSTER['UNIQUE_JOIN'].str.replace('+','', regex=True)


##############################################################################

#######################################################################################
##                                                                                   ##
##                                 40+ YD pass/rec data                              ##
##                                                                                   ##
#######################################################################################

#######################################################################################
##                                                                                   ##
##                               bring in Roster data                                ##
##                                                                                   ##
#######################################################################################

df_ROSTER = pd.read_csv(r'D:\Geoff\Analytics\Fantasy Football\Reference\NFL_ROSTER.csv')

df_ROSTER = df_ROSTER.filter(['Player','Pos'])


#######################################################################################
##                                                                                   ##
##                                 40+ YD pass data                                  ##
##                                                                                   ##
#######################################################################################


df_40YD_PASS_CUR = pd.read_html('https://www.nfl.com/stats/player-stats/category/passing/' + year_current + '/post/all/passingyards/desc')
df_40YD_PASS_PRIOR1 = pd.read_html('https://www.nfl.com/stats/player-stats/category/passing/' + year_prior1 + '/post/all/passingyards/desc')
df_40YD_PASS_PRIOR2 = pd.read_html('https://www.nfl.com/stats/player-stats/category/passing/' + year_prior2 + '/post/all/passingyards/desc')

df_40YD_PASS_CUR = df_40YD_PASS_CUR[-1]
df_40YD_PASS_PRIOR1 = df_40YD_PASS_PRIOR1[-1]
df_40YD_PASS_PRIOR2 = df_40YD_PASS_PRIOR2[-1]

df_40YD_PASS_CUR['FANTASY_YEAR'] = year_current
df_40YD_PASS_PRIOR1['FANTASY_YEAR'] = year_prior1
df_40YD_PASS_PRIOR2['FANTASY_YEAR'] = year_prior2

df_40YD_PASS_CUR = df_40YD_PASS_CUR.filter(['Player','40+','FANTASY_YEAR'])
df_40YD_PASS_PRIOR1 = df_40YD_PASS_PRIOR1.filter(['Player','40+','FANTASY_YEAR'])
df_40YD_PASS_PRIOR2 = df_40YD_PASS_PRIOR2.filter(['Player','40+','FANTASY_YEAR'])

df_40YD_PASS_ALL = pd.concat([df_40YD_PASS_CUR, df_40YD_PASS_PRIOR1,df_40YD_PASS_PRIOR2]).drop_duplicates()

df_40YD_PASS_ALL = pd.merge(df_40YD_PASS_ALL,df_ROSTER, on='Player',how='left').fillna(0).drop_duplicates()

df_40YD_PASS_ALL['UNIQUE_JOIN'] = df_40YD_PASS_ALL['Player'].astype(str) + df_40YD_PASS_ALL['Pos'].astype(str) + df_40YD_PASS_ALL['FANTASY_YEAR'].astype(str)

df_40YD_PASS_ALL['40_YD_PASS'] = df_40YD_PASS_ALL['40+']

df_40YD_PASS_ALL = df_40YD_PASS_ALL.filter(['UNIQUE_JOIN','40_YD_PASS'])

#######################################################################################
##                                                                                   ##
##                                 40+ YD rec data                                   ##
##                                                                                   ##
#######################################################################################

df_40YD_REC_CUR = pd.read_html('https://www.nfl.com/stats/player-stats/category/receiving/' + year_current + '/post/all/receivingreceptions/desc')
df_40YD_REC_PRIOR1 = pd.read_html('https://www.nfl.com/stats/player-stats/category/receiving/' + year_prior1 + '/post/all/receivingreceptions/desc')
df_40YD_REC_PRIOR2 = pd.read_html('https://www.nfl.com/stats/player-stats/category/receiving/' + year_prior2 + '/post/all/receivingreceptions/desc')

df_40YD_REC_CUR = df_40YD_REC_CUR[-1]
df_40YD_REC_PRIOR1 = df_40YD_REC_PRIOR1[-1]
df_40YD_REC_PRIOR2 = df_40YD_REC_PRIOR2[-1]

df_40YD_REC_CUR['FANTASY_YEAR'] = year_current
df_40YD_REC_PRIOR1['FANTASY_YEAR'] = year_prior1
df_40YD_REC_PRIOR2['FANTASY_YEAR'] = year_prior2

df_40YD_REC_CUR = df_40YD_REC_CUR.filter(['Player','40+','FANTASY_YEAR'])
df_40YD_REC_PRIOR1 = df_40YD_REC_PRIOR1.filter(['Player','40+','FANTASY_YEAR'])
df_40YD_REC_PRIOR2 = df_40YD_REC_PRIOR2.filter(['Player','40+','FANTASY_YEAR'])

df_40YD_REC_ALL = pd.concat([df_40YD_REC_CUR, df_40YD_REC_PRIOR1,df_40YD_REC_PRIOR2]).drop_duplicates()

df_40YD_REC_ALL = pd.merge(df_40YD_REC_ALL,df_ROSTER, on='Player',how='left').fillna(0).drop_duplicates()

df_40YD_REC_ALL['UNIQUE_JOIN'] = df_40YD_REC_ALL['Player'].astype(str) + df_40YD_REC_ALL['Pos'].astype(str) + df_40YD_REC_ALL['FANTASY_YEAR'].astype(str)

df_40YD_REC_ALL['40_YD_REC'] = df_40YD_REC_ALL['40+']

df_40YD_REC_ALL = df_40YD_REC_ALL.filter(['UNIQUE_JOIN','40_YD_REC'])

#######################################################################################

df_OFF_KPI_ROSTER = pd.merge(df_OFF_KPI_ROSTER,df_40YD_PASS_ALL, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()
df_OFF_KPI_ROSTER = pd.merge(df_OFF_KPI_ROSTER,df_40YD_REC_ALL, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

#######################################################################################


#######################################################################################
##                                                                                   ##
##                       Calculate Total Offensive KPI's                             ##
##                                                                                   ##
#######################################################################################

##############
# KPI Score Metrics

PASS_YDS_METRIC = 25
PASS_TD_METRIC = 4
PASS_INT_METRIC = (-2)
PASS_SACK_METRIC = (-1)

RUSH_YDS_METRIC = 10
RUSH_TD_METRIC = 6

REC_YDS_METRIC = 10
REC_CATCH_METRIC = 1
REC_TD_METRIC = 6

OFF_FUMBLE_METRIC = (-2)

OFF_40YD_PASS_METRIC = 1
OFF_40YD_REC_METRIC = 1


DF_1 = df_OFF_KPI_ROSTER

## Define KPI Score

DF_1['PASSING_YDS_SCORE'] = DF_1['PASSING_YDS'] / PASS_YDS_METRIC
DF_1['PASSING_TD_SCORE'] = DF_1['PASSING_TD'] * PASS_TD_METRIC
DF_1['PASSING_INT_SCORE'] = DF_1['PASSING_INT'] * PASS_INT_METRIC
DF_1['PASSING_SACK_SCORE'] = DF_1['PASSING_SACK'] * PASS_SACK_METRIC
DF_1['RUSH_YDS_SCORE'] = DF_1['RUSH_YDS'] / RUSH_YDS_METRIC
DF_1['RUSH_TD_SCORE'] = DF_1['RUSH_TD'] * RUSH_TD_METRIC
DF_1['REC_YDS_SCORE'] = DF_1['REC_YDS'] / REC_YDS_METRIC
DF_1['REC_CATCH_SCORE'] = DF_1['REC_CATCH'] * REC_CATCH_METRIC
DF_1['REC_TD_SCORE'] = DF_1['REC_TD'] * REC_TD_METRIC
DF_1['OFF_FMBL_SCORE'] = DF_1['OFF_FMBL'] * OFF_FUMBLE_METRIC
DF_1['OFF_40YD_PASS_SCORE'] = DF_1['40_YD_PASS'] * OFF_40YD_PASS_METRIC
DF_1['OFF_40YD_REC_SCORE'] = DF_1['40_YD_REC'] * OFF_40YD_REC_METRIC

DF_1['YTD_PASS_SCORE'] = DF_1['PASSING_YDS_SCORE'] + DF_1['PASSING_TD_SCORE'] + DF_1['PASSING_INT_SCORE'] + DF_1['PASSING_SACK_SCORE'] + DF_1['OFF_40YD_PASS_SCORE']
DF_1['YTD_RUSH_SCORE'] = DF_1['RUSH_YDS_SCORE'] + DF_1['RUSH_TD_SCORE']
DF_1['YTD_REC_SCORE'] = DF_1['REC_YDS_SCORE'] + DF_1['REC_TD_SCORE'] + DF_1['REC_CATCH_SCORE'] + DF_1['OFF_40YD_REC_SCORE']

DF_1['YTD_SCORE'] = DF_1['YTD_PASS_SCORE'] + DF_1['YTD_RUSH_SCORE'] + DF_1['YTD_REC_SCORE']

# Define Weekly KPI's
DF_1['WEEKLY_PASS_SCORE'] = DF_1['YTD_PASS_SCORE'] /DF_1['GAMES_PLAYED']
DF_1['WEEKLY_RUSH_SCORE'] = DF_1['YTD_RUSH_SCORE'] /DF_1['GAMES_PLAYED']
DF_1['WEEKLY_REC_SCORE'] = DF_1['YTD_REC_SCORE'] /DF_1['GAMES_PLAYED']

DF_1['WEEKLY_SCORE'] = DF_1['YTD_SCORE'] /DF_1['GAMES_PLAYED']

df_OFF_KPI_SCORE = DF_1.filter(['UNIQUE_JOIN',
                                'YTD_PASS_SCORE',
                                'YTD_RUSH_SCORE',
                                'YTD_REC_SCORE',
                                'WEEKLY_PASS_SCORE',
                                'WEEKLY_RUSH_SCORE',
                                'WEEKLY_REC_SCORE'
                                ])

df_OFF_KPI_ROSTER = DF_1.filter(['UNIQUE_JOIN',
                                 'PLAYER_NAME',
                                 'PLAYER_POSITION',
                                 'GAMES_PLAYED',
                                 'FANTASY_YEAR',
                                 'YTD_SCORE',
                                 'WEEKLY_SCORE'
                                ])

#define condition of each value
conditions = [
    (df_OFF_KPI_ROSTER['WEEKLY_SCORE'] <= 5),
    (df_OFF_KPI_ROSTER['WEEKLY_SCORE'] <= 10),
    (df_OFF_KPI_ROSTER['WEEKLY_SCORE'] <= 15),
    (df_OFF_KPI_ROSTER['WEEKLY_SCORE'] <= 25),
    (df_OFF_KPI_ROSTER['WEEKLY_SCORE'] > 25)
]

# Define result depending on the condition met
values = ["Under 5","5 - 10","10 - 15","15 - 25","Over 25"]

# Apply Condition -> result logic as a new column in the DataFrame
df_OFF_KPI_ROSTER['WEEKLY_SCORE_GROUP'] = np.select(conditions, values)


##############################################################################

## Define Fantasy Year Group
year_current_val = int(Year_Variable)

#define condition of each value
conditions = [
    (df_OFF_KPI_ROSTER['FANTASY_YEAR'] == year_current),
    (df_OFF_KPI_ROSTER['FANTASY_YEAR'] == year_prior1),
    (df_OFF_KPI_ROSTER['FANTASY_YEAR'] == year_prior2)
]

# Define result depending on the condition met
values = ["Current Year","Prior Year","Two Years Ago"]

# Apply Condition -> result logic as a new column in the DataFrame
df_OFF_KPI_ROSTER['FANTASY_YEAR_GROUP'] = np.select(conditions, values)


##############################################################################


#######################################################################################
##                                                                                   ##
##                              Create weekly kpi scores                             ##
##                                                                                   ##
#######################################################################################

#df_OFF_KPI_SCORE
df_OFF_KPI_SCORE.to_csv(r'D:\Geoff\Analytics\Fantasy Football\PBI Source Data\OFF_KPI_SCORE.csv', index=False)

##############################################################################




print('<<<<<<<<<<<<<<>>>>>>>>>>>>>>')
print('        OFF_KPI_ROSTER')
df_OFF_KPI_ROSTER.info()
df_OFF_KPI_ROSTER.head(5)

<<<<<<<<<<<<<<>>>>>>>>>>>>>>
        OFF_KPI_ROSTER
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1889 entries, 0 to 1888
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   UNIQUE_JOIN         1889 non-null   object
 1   PLAYER_NAME         1889 non-null   object
 2   PLAYER_POSITION     1889 non-null   object
 3   GAMES_PLAYED        1889 non-null   int32
 4   FANTASY_YEAR        1889 non-null   object
 5   YTD_SCORE           1889 non-null   float64
 6   WEEKLY_SCORE        1889 non-null   float64
 7   WEEKLY_SCORE_GROUP  1889 non-null   object
 8   FANTASY_YEAR_GROUP  1889 non-null   object
dtypes: float64(2), int32(1), object(6)
memory usage: 140.2+ KB

,UNIQUE_JOIN,PLAYER_NAME,PLAYER_POSITION,GAMES_PLAYED,FANTASY_YEAR,YTD_SCORE,WEEKLY_SCORE,WEEKLY_SCORE_GROUP,FANTASY_YEAR_GROUP
0,Patrick MahomesQB2022,Patrick Mahomes,QB,17,2022,398.40,23.435294,15 - 25,Current Year
1,Justin HerbertQB2022,Justin Herbert,QB,17,2022,254.26,14.956471,10 - 15,Current Year
2,Tom BradyQB2022,Tom Brady,QB,17,2022,253.66,14.921176,10 - 15,Current Year
3,Kirk CousinsQB2022,Kirk Cousins,QB,17,2022,255.58,15.034118,15 - 25,Current Year
4,Joe BurrowQB2022,Joe Burrow,QB,16,2022,319.70,19.981250,15 - 25,Current Year

In [6]:
#######################################################################################
##                                                                                   ##
##            build out a single DataFrame with 3 years of Defense                   ##
##                                                                                   ##
#######################################################################################


"""
Define Weekly Defense data points:

Points Against -> this one comes from a manual excel file print('sigh')
Sack
Interception
Fumble Recovery
TD

"""

#######################################################################################
##                                                                                   ##
##                             Defense Points Against                                ##
##                                                                                   ##
#######################################################################################


DF_POINTS_AGAINST = pd.read_csv(r'D:\Geoff\Analytics\Fantasy Football\Reference\DEF_SCORE_AGAINST.csv')

DF_POINTS_AGAINST['PLAYER_POSITION'] = "DEF/ST"
DF_POINTS_AGAINST['UNIQUE_JOIN'] = DF_POINTS_AGAINST['PLAYER_NAME'] + DF_POINTS_AGAINST['PLAYER_POSITION'] + DF_POINTS_AGAINST['FANTASY_YEAR'].astype(str)


#define condition of each value

# Standard Points Against score group values
DEFAULT_VALUE_LIST = [10,7,4,1,0,-1,-4]

# Define score for each week
conditions = [
    (DF_POINTS_AGAINST['WEEK_1'] <= 0),
    (DF_POINTS_AGAINST['WEEK_1'] <= 6),
    (DF_POINTS_AGAINST['WEEK_1'] <= 13),
    (DF_POINTS_AGAINST['WEEK_1'] <= 20),
    (DF_POINTS_AGAINST['WEEK_1'] <= 27),
    (DF_POINTS_AGAINST['WEEK_1'] <= 34),
    (DF_POINTS_AGAINST['WEEK_1'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_1_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_2'] <= 0),
    (DF_POINTS_AGAINST['WEEK_2'] <= 6),
    (DF_POINTS_AGAINST['WEEK_2'] <= 13),
    (DF_POINTS_AGAINST['WEEK_2'] <= 20),
    (DF_POINTS_AGAINST['WEEK_2'] <= 27),
    (DF_POINTS_AGAINST['WEEK_2'] <= 34),
    (DF_POINTS_AGAINST['WEEK_2'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_2_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_3'] <= 0),
    (DF_POINTS_AGAINST['WEEK_3'] <= 6),
    (DF_POINTS_AGAINST['WEEK_3'] <= 13),
    (DF_POINTS_AGAINST['WEEK_3'] <= 20),
    (DF_POINTS_AGAINST['WEEK_3'] <= 27),
    (DF_POINTS_AGAINST['WEEK_3'] <= 34),
    (DF_POINTS_AGAINST['WEEK_3'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_3_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_4'] <= 0),
    (DF_POINTS_AGAINST['WEEK_4'] <= 6),
    (DF_POINTS_AGAINST['WEEK_4'] <= 13),
    (DF_POINTS_AGAINST['WEEK_4'] <= 20),
    (DF_POINTS_AGAINST['WEEK_4'] <= 27),
    (DF_POINTS_AGAINST['WEEK_4'] <= 34),
    (DF_POINTS_AGAINST['WEEK_4'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_4_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_5'] <= 0),
    (DF_POINTS_AGAINST['WEEK_5'] <= 6),
    (DF_POINTS_AGAINST['WEEK_5'] <= 13),
    (DF_POINTS_AGAINST['WEEK_5'] <= 20),
    (DF_POINTS_AGAINST['WEEK_5'] <= 27),
    (DF_POINTS_AGAINST['WEEK_5'] <= 34),
    (DF_POINTS_AGAINST['WEEK_5'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_5_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_6'] <= 0),
    (DF_POINTS_AGAINST['WEEK_6'] <= 6),
    (DF_POINTS_AGAINST['WEEK_6'] <= 13),
    (DF_POINTS_AGAINST['WEEK_6'] <= 20),
    (DF_POINTS_AGAINST['WEEK_6'] <= 27),
    (DF_POINTS_AGAINST['WEEK_6'] <= 34),
    (DF_POINTS_AGAINST['WEEK_6'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_6_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_7'] <= 0),
    (DF_POINTS_AGAINST['WEEK_7'] <= 6),
    (DF_POINTS_AGAINST['WEEK_7'] <= 13),
    (DF_POINTS_AGAINST['WEEK_7'] <= 20),
    (DF_POINTS_AGAINST['WEEK_7'] <= 27),
    (DF_POINTS_AGAINST['WEEK_7'] <= 34),
    (DF_POINTS_AGAINST['WEEK_7'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_7_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_8'] <= 0),
    (DF_POINTS_AGAINST['WEEK_8'] <= 6),
    (DF_POINTS_AGAINST['WEEK_8'] <= 13),
    (DF_POINTS_AGAINST['WEEK_8'] <= 20),
    (DF_POINTS_AGAINST['WEEK_8'] <= 27),
    (DF_POINTS_AGAINST['WEEK_8'] <= 34),
    (DF_POINTS_AGAINST['WEEK_8'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_8_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_9'] <= 0),
    (DF_POINTS_AGAINST['WEEK_9'] <= 6),
    (DF_POINTS_AGAINST['WEEK_9'] <= 13),
    (DF_POINTS_AGAINST['WEEK_9'] <= 20),
    (DF_POINTS_AGAINST['WEEK_9'] <= 27),
    (DF_POINTS_AGAINST['WEEK_9'] <= 34),
    (DF_POINTS_AGAINST['WEEK_9'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_9_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_10'] <= 0),
    (DF_POINTS_AGAINST['WEEK_10'] <= 6),
    (DF_POINTS_AGAINST['WEEK_10'] <= 13),
    (DF_POINTS_AGAINST['WEEK_10'] <= 20),
    (DF_POINTS_AGAINST['WEEK_10'] <= 27),
    (DF_POINTS_AGAINST['WEEK_10'] <= 34),
    (DF_POINTS_AGAINST['WEEK_10'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_10_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_11'] <= 0),
    (DF_POINTS_AGAINST['WEEK_11'] <= 6),
    (DF_POINTS_AGAINST['WEEK_11'] <= 13),
    (DF_POINTS_AGAINST['WEEK_11'] <= 20),
    (DF_POINTS_AGAINST['WEEK_11'] <= 27),
    (DF_POINTS_AGAINST['WEEK_11'] <= 34),
    (DF_POINTS_AGAINST['WEEK_11'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_11_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_12'] <= 0),
    (DF_POINTS_AGAINST['WEEK_12'] <= 6),
    (DF_POINTS_AGAINST['WEEK_12'] <= 13),
    (DF_POINTS_AGAINST['WEEK_12'] <= 20),
    (DF_POINTS_AGAINST['WEEK_12'] <= 27),
    (DF_POINTS_AGAINST['WEEK_12'] <= 34),
    (DF_POINTS_AGAINST['WEEK_12'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_12_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_13'] <= 0),
    (DF_POINTS_AGAINST['WEEK_13'] <= 6),
    (DF_POINTS_AGAINST['WEEK_13'] <= 13),
    (DF_POINTS_AGAINST['WEEK_13'] <= 20),
    (DF_POINTS_AGAINST['WEEK_13'] <= 27),
    (DF_POINTS_AGAINST['WEEK_13'] <= 34),
    (DF_POINTS_AGAINST['WEEK_13'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_13_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_14'] <= 0),
    (DF_POINTS_AGAINST['WEEK_14'] <= 6),
    (DF_POINTS_AGAINST['WEEK_14'] <= 13),
    (DF_POINTS_AGAINST['WEEK_14'] <= 20),
    (DF_POINTS_AGAINST['WEEK_14'] <= 27),
    (DF_POINTS_AGAINST['WEEK_14'] <= 34),
    (DF_POINTS_AGAINST['WEEK_14'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_14_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_15'] <= 0),
    (DF_POINTS_AGAINST['WEEK_15'] <= 6),
    (DF_POINTS_AGAINST['WEEK_15'] <= 13),
    (DF_POINTS_AGAINST['WEEK_15'] <= 20),
    (DF_POINTS_AGAINST['WEEK_15'] <= 27),
    (DF_POINTS_AGAINST['WEEK_15'] <= 34),
    (DF_POINTS_AGAINST['WEEK_15'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_15_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_16'] <= 0),
    (DF_POINTS_AGAINST['WEEK_16'] <= 6),
    (DF_POINTS_AGAINST['WEEK_16'] <= 13),
    (DF_POINTS_AGAINST['WEEK_16'] <= 20),
    (DF_POINTS_AGAINST['WEEK_16'] <= 27),
    (DF_POINTS_AGAINST['WEEK_16'] <= 34),
    (DF_POINTS_AGAINST['WEEK_16'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_16_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_17'] <= 0),
    (DF_POINTS_AGAINST['WEEK_17'] <= 6),
    (DF_POINTS_AGAINST['WEEK_17'] <= 13),
    (DF_POINTS_AGAINST['WEEK_17'] <= 20),
    (DF_POINTS_AGAINST['WEEK_17'] <= 27),
    (DF_POINTS_AGAINST['WEEK_17'] <= 34),
    (DF_POINTS_AGAINST['WEEK_17'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_17_SCORE'] = np.select(conditions, values)

conditions = [
    (DF_POINTS_AGAINST['WEEK_18'] <= 0),
    (DF_POINTS_AGAINST['WEEK_18'] <= 6),
    (DF_POINTS_AGAINST['WEEK_18'] <= 13),
    (DF_POINTS_AGAINST['WEEK_18'] <= 20),
    (DF_POINTS_AGAINST['WEEK_18'] <= 27),
    (DF_POINTS_AGAINST['WEEK_18'] <= 34),
    (DF_POINTS_AGAINST['WEEK_18'] >= 35)
]

# Define result depending on the condition met
values = DEFAULT_VALUE_LIST

# Apply Condition -> result logic as a new column in the DataFrame
DF_POINTS_AGAINST['WEEK_18_SCORE'] = np.select(conditions, values)

DF_POINTS_AGAINST['TOTAL_POINTS_AGAINST_SCORE'] = DF_POINTS_AGAINST['WEEK_1_SCORE'] + DF_POINTS_AGAINST['WEEK_2_SCORE'] + DF_POINTS_AGAINST['WEEK_3_SCORE'] + DF_POINTS_AGAINST['WEEK_4_SCORE'] + DF_POINTS_AGAINST['WEEK_5_SCORE'] + DF_POINTS_AGAINST['WEEK_6_SCORE'] + DF_POINTS_AGAINST['WEEK_7_SCORE'] + DF_POINTS_AGAINST['WEEK_8_SCORE'] + DF_POINTS_AGAINST['WEEK_9_SCORE'] + DF_POINTS_AGAINST['WEEK_10_SCORE'] + DF_POINTS_AGAINST['WEEK_11_SCORE'] + DF_POINTS_AGAINST['WEEK_12_SCORE'] + DF_POINTS_AGAINST['WEEK_13_SCORE'] + DF_POINTS_AGAINST['WEEK_14_SCORE'] + DF_POINTS_AGAINST['WEEK_15_SCORE'] + DF_POINTS_AGAINST['WEEK_16_SCORE'] + DF_POINTS_AGAINST['WEEK_17_SCORE'] + DF_POINTS_AGAINST['WEEK_18_SCORE']

DF_POINTS_AGAINST['FANTASY_YEAR'] = DF_POINTS_AGAINST['FANTASY_YEAR'].astype(str)

# moving down in logic
#DF_POINTS_AGAINST['WEEKLY_POINTS_AGAINST_SCORE'] = DF_POINTS_AGAINST['TOTAL_POINTS_AGAINST_SCORE'] / DF_POINTS_AGAINST['GAMES_PLAYED']

DF_POINTS_AGAINST = DF_POINTS_AGAINST.filter(['FANTASY_YEAR',
                                              'UNIQUE_JOIN',
                                              'PLAYER_NAME',
                                              'PLAYER_POSITION',
                                              'GAMES_PLAYED',
                                              'TOTAL_POINTS_AGAINST_SCORE'
                                             ])

df_DEF_TEAM_BIO = DF_POINTS_AGAINST.filter(['UNIQUE_JOIN',
                                            'FANTASY_YEAR',
                                            'PLAYER_NAME',
                                            'PLAYER_POSITION',
                                            'GAMES_PLAYED'
                                           ])

df_DEF_TEAM_KPI = DF_POINTS_AGAINST.filter(['UNIQUE_JOIN',
                                            'TOTAL_POINTS_AGAINST_SCORE'
                                           ])


#######################################################################################
##                                                                                   ##
##                             Defense remainig KPI's                                ##
##                                                                                   ##
#######################################################################################


df_DEF_CURRNET = pd.read_html('https://www.pro-football-reference.com/years/' + year_current + '/defense.htm', header=1)
df_DEF_PRIOR1 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior1 + '/defense.htm', header=1)
df_DEF_PRIOR2 = pd.read_html('https://www.pro-football-reference.com/years/' + year_prior2 + '/defense.htm', header=1)

df_DEF_CURRNET = df_DEF_CURRNET[-1]
df_DEF_PRIOR1 = df_DEF_PRIOR1[-1]
df_DEF_PRIOR2 = df_DEF_PRIOR2[-1]

df_DEF_CURRNET = df_DEF_CURRNET[df_DEF_CURRNET['Player'] != 'Player']
df_DEF_PRIOR1 = df_DEF_PRIOR1[df_DEF_PRIOR1['Player'] != 'Player']
df_DEF_PRIOR2 = df_DEF_PRIOR2[df_DEF_PRIOR2['Player'] != 'Player']


## build a dictionairy to convert to a DataFrame to clean up columns
df_DEF_CURRENT_dict = {'PLAYER_NAME_SOURCE': df_DEF_CURRNET['Player'].fillna("N"),
                        'PLAYER_TEAM_NAME_SOURCE': df_DEF_CURRNET['Tm'].fillna("N"),
                        'PLAYER_POSITION': "DEF/ST",
                        'FANTASY_YEAR': year_current,
                        'TOTAL_INT_DEF': df_DEF_CURRNET['Int'].astype(float).fillna(0),
                        'TOTAL_FMBL_DEF': df_DEF_CURRNET['FR'].fillna(0).astype(int), # -> this is Fumbles Recovered
                        'TOTAL_SACK_DEF': df_DEF_CURRNET['Sk'].fillna(0).astype(float),
                        'TOTAL_SFTY_DEF': df_DEF_CURRNET['Sfty'].fillna(0).astype(int),
                        'TOTAL_TD_DEF': df_DEF_CURRNET['TD'].fillna(0).astype(int) + df_DEF_CURRNET['TD.1'].fillna(0).astype(int)
                       }

#convert the dictionairy to a DataFrame
df_DEF_CURRENT = pd.DataFrame(df_DEF_CURRENT_dict)

## build a dictionairy to convert to a DataFrame to clean up columns
df_DEF_PRIOR1_dict = {'PLAYER_NAME_SOURCE': df_DEF_PRIOR1['Player'].fillna("N"),
                        'PLAYER_TEAM_NAME_SOURCE': df_DEF_PRIOR1['Tm'].fillna("N"),
                        'PLAYER_POSITION': "DEF/ST",
                        'FANTASY_YEAR': year_prior1,
                        'TOTAL_INT_DEF': df_DEF_PRIOR1['Int'].astype(float).fillna(0),
                        'TOTAL_FMBL_DEF': df_DEF_PRIOR1['FR'].fillna(0).astype(int), # -> this is Fumbles Recovered
                        'TOTAL_SACK_DEF': df_DEF_PRIOR1['Sk'].fillna(0).astype(float),
                        'TOTAL_SFTY_DEF': df_DEF_PRIOR1['Sfty'].fillna(0).astype(int),
                        'TOTAL_TD_DEF': df_DEF_PRIOR1['TD'].fillna(0).astype(int) + df_DEF_PRIOR1['TD.1'].fillna(0).astype(int)
                       }

#convert the dictionairy to a DataFrame
df_DEF_PRIOR1 = pd.DataFrame(df_DEF_PRIOR1_dict)

## build a dictionairy to convert to a DataFrame to clean up columns
df_DEF_PRIOR2_dict = {'PLAYER_NAME_SOURCE': df_DEF_PRIOR2['Player'].fillna("N"),
                        'PLAYER_TEAM_NAME_SOURCE': df_DEF_PRIOR2['Tm'].fillna("N"),
                        'PLAYER_POSITION': "DEF/ST",
                        'FANTASY_YEAR': year_prior2,
                        'TOTAL_INT_DEF': df_DEF_PRIOR2['Int'].astype(float).fillna(0),
                        'TOTAL_FMBL_DEF': df_DEF_PRIOR2['FR'].fillna(0).astype(int), # -> this is Fumbles Recovered
                        'TOTAL_SACK_DEF': df_DEF_PRIOR2['Sk'].fillna(0).astype(float),
                        'TOTAL_SFTY_DEF': df_DEF_PRIOR2['Sfty'].fillna(0).astype(int),
                        'TOTAL_TD_DEF': df_DEF_PRIOR2['TD'].fillna(0).astype(int) + df_DEF_PRIOR2['TD.1'].fillna(0).astype(int)
                       }

#convert the dictionairy to a DataFrame
df_DEF_PRIOR2 = pd.DataFrame(df_DEF_PRIOR2_dict)


df_DEF_PLAYER_KPI_ALL = pd.concat([df_DEF_CURRENT, df_DEF_PRIOR1,df_DEF_PRIOR2])


"""

Need to clean up players that were traded mid season
Data will follow the player to the new team

"""
#define condition of each value
conditions = [
    (df_DEF_PLAYER_KPI_ALL['PLAYER_NAME_SOURCE'] == "Roquan Smith*+"),
    (df_DEF_PLAYER_KPI_ALL['PLAYER_NAME_SOURCE'] == "Justin Hollins")
]

# Define result depending on the condition met
values = ['BAL','LAR']

# Apply Condition -> result logic as a new column in the DataFrame
df_DEF_PLAYER_KPI_ALL['PLAYER_TEAM_NAME_CALC'] = np.select(conditions, values)

#define condition of each value
conditions = [
    (df_DEF_PLAYER_KPI_ALL['PLAYER_TEAM_NAME_CALC'] == "0"),
    (df_DEF_PLAYER_KPI_ALL['PLAYER_NAME_SOURCE'] != "0")
]

# Define result depending on the condition met
values = [df_DEF_PLAYER_KPI_ALL['PLAYER_TEAM_NAME_SOURCE'],df_DEF_PLAYER_KPI_ALL['PLAYER_TEAM_NAME_CALC']]

# Apply Condition -> result logic as a new column in the DataFrame
df_DEF_PLAYER_KPI_ALL['PLAYER_NAME'] = np.select(conditions, values)

df_DEF_PLAYER_KPI_ALL['UNIQUE_JOIN'] = df_DEF_PLAYER_KPI_ALL['PLAYER_NAME'] + df_DEF_PLAYER_KPI_ALL['PLAYER_POSITION'] + df_DEF_PLAYER_KPI_ALL['FANTASY_YEAR'] 


#######################################################################################
##                                                                                   ##
##                             Defense final scores                                  ##
##                                                                                   ##
#######################################################################################


df_1 = DF_POINTS_AGAINST.filter(['UNIQUE_JOIN',
                                 'FANTASY_YEAR',
                                 'GAMES_PLAYED'
                                ]).drop_duplicates()

df_DEF_PLAYER_BIO = df_DEF_PLAYER_KPI_ALL.filter(['UNIQUE_JOIN',
                                                  'PLAYER_NAME',
                                                  'PLAYER_POSITION'
                                                 ]).drop_duplicates()

df_1 = pd.merge(df_1,df_DEF_PLAYER_BIO, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

df_DEF_PLAYER_BIO = df_1

df_DEF_PLAYER_KPI = df_DEF_PLAYER_KPI_ALL.filter(['UNIQUE_JOIN',
                                                  'TOTAL_INT_DEF',
                                                  'TOTAL_FMBL_DEF',
                                                  'TOTAL_SACK_DEF',
                                                  'TOTAL_SFTY_DEF',
                                                  'TOTAL_TD_DEF'
                                                 ]).drop_duplicates()

df_DEF_PLAYER_KPI = df_DEF_PLAYER_KPI.groupby('UNIQUE_JOIN').sum()

df_2 = DF_POINTS_AGAINST.filter(['UNIQUE_JOIN']).drop_duplicates()

df_DEF_PLAYER_KPI = pd.merge(df_2,df_DEF_PLAYER_KPI, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()


DEF_SACK_METRIC = 1
DEF_INT_METRIC = 2
DEF_FMBL_METRIC = 2
DEF_TD_METRIC = 6
DEF_SFTY_METRIC = 2

df_DEF_PLAYER_KPI['DEF_INT_SCORE'] = df_DEF_PLAYER_KPI['TOTAL_INT_DEF'] * DEF_INT_METRIC
df_DEF_PLAYER_KPI['DEF_FMBL_SCORE'] = df_DEF_PLAYER_KPI['TOTAL_FMBL_DEF'] * DEF_FMBL_METRIC
df_DEF_PLAYER_KPI['DEF_SACK_SCORE'] = df_DEF_PLAYER_KPI['TOTAL_SACK_DEF'] * DEF_SACK_METRIC
df_DEF_PLAYER_KPI['DEF_SFTY_SCORE'] = df_DEF_PLAYER_KPI['TOTAL_SFTY_DEF'] * DEF_SFTY_METRIC
df_DEF_PLAYER_KPI['DEF_TD_SCORE'] = df_DEF_PLAYER_KPI['TOTAL_TD_DEF'] * DEF_TD_METRIC
df_DEF_PLAYER_KPI['DEF_PLAYER_YTD_SCORE'] = df_DEF_PLAYER_KPI['DEF_INT_SCORE'] + df_DEF_PLAYER_KPI['DEF_FMBL_SCORE'] + df_DEF_PLAYER_KPI['DEF_SACK_SCORE'] + df_DEF_PLAYER_KPI['DEF_SFTY_SCORE'] + df_DEF_PLAYER_KPI['DEF_TD_SCORE']


## build a dictionairy to convert to a DataFrame to clean up columns
df_DEF_PLAYER_KPI_dict = {'UNIQUE_JOIN': df_DEF_PLAYER_KPI['UNIQUE_JOIN'].fillna("N"),
                          'DEF_PLAYER_YTD_SCORE': df_DEF_PLAYER_KPI['DEF_PLAYER_YTD_SCORE'].fillna(0)
                         }

#convert the dictionairy to a DataFrame
df_DEF_PLAYER_KPI = pd.DataFrame(df_DEF_PLAYER_KPI_dict)

#######################################################################################
##                                                                                   ##
##                             Defense final data sets                               ##
##                                                                                   ##
#######################################################################################

df_DEFENSE_KPI_ROSTER = pd.concat([df_DEF_PLAYER_BIO, df_DEF_TEAM_BIO]).drop_duplicates()

df_DEFENSE_KPI_ROSTER = pd.merge(df_DEFENSE_KPI_ROSTER,df_DEF_TEAM_KPI, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()
df_DEFENSE_KPI_ROSTER = pd.merge(df_DEFENSE_KPI_ROSTER,df_DEF_PLAYER_KPI, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

df_DEFENSE_KPI_ROSTER['YTD_SCORE'] = df_DEFENSE_KPI_ROSTER['TOTAL_POINTS_AGAINST_SCORE'] + df_DEFENSE_KPI_ROSTER['DEF_PLAYER_YTD_SCORE']
df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE'] = df_DEFENSE_KPI_ROSTER['YTD_SCORE'] / df_DEFENSE_KPI_ROSTER['GAMES_PLAYED']


df_DEFENSE_KPI_ROSTER = df_DEFENSE_KPI_ROSTER.filter(['UNIQUE_JOIN',
                                                      'PLAYER_NAME',
                                                      'PLAYER_POSITION',
                                                      'GAMES_PLAYED',                                                      
                                                      'FANTASY_YEAR',
                                                      'YTD_SCORE',
                                                      'WEEKLY_SCORE'
                                                     ])
#define condition of each value
conditions = [
    (df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE'] <= 5),
    (df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE'] <= 10),
    (df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE'] <= 15),
    (df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE'] <= 25),
    (df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE'] > 25)
]

# Define result depending on the condition met
values = ["Under 5","5 - 10","10 - 15","15 - 25","Over 25"]

# Apply Condition -> result logic as a new column in the DataFrame
df_DEFENSE_KPI_ROSTER['WEEKLY_SCORE_GROUP'] = np.select(conditions, values)

##############################################################################

## Define Fantasy Year Group
year_current_val = int(Year_Variable)

#define condition of each value
conditions = [
    (df_DEFENSE_KPI_ROSTER['FANTASY_YEAR'] == year_current),
    (df_DEFENSE_KPI_ROSTER['FANTASY_YEAR'] == year_prior1),
    (df_DEFENSE_KPI_ROSTER['FANTASY_YEAR'] == year_prior2)
]

# Define result depending on the condition met
values = ["Current Year","Prior Year","Two Years Ago"]

# Apply Condition -> result logic as a new column in the DataFrame
df_DEFENSE_KPI_ROSTER['FANTASY_YEAR_GROUP'] = np.select(conditions, values)


##############################################################################


print('<<<<<<<<<<<<<<>>>>>>>>>>>>>>')
print('        DEF_KPI_ROSTER')
df_DEFENSE_KPI_ROSTER.info()
df_DEFENSE_KPI_ROSTER

<<<<<<<<<<<<<<>>>>>>>>>>>>>>
        DEF_KPI_ROSTER
<class 'pandas.core.frame.DataFrame'>
Int64Index: 96 entries, 0 to 95
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   UNIQUE_JOIN         96 non-null     object
 1   PLAYER_NAME         96 non-null     object
 2   PLAYER_POSITION     96 non-null     object
 3   GAMES_PLAYED        96 non-null     int64
 4   FANTASY_YEAR        96 non-null     object
 5   YTD_SCORE           96 non-null     float64
 6   WEEKLY_SCORE        96 non-null     float64
 7   WEEKLY_SCORE_GROUP  96 non-null     object
 8   FANTASY_YEAR_GROUP  96 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 7.5+ KB

,UNIQUE_JOIN,PLAYER_NAME,PLAYER_POSITION,GAMES_PLAYED,FANTASY_YEAR,YTD_SCORE,WEEKLY_SCORE,WEEKLY_SCORE_GROUP,FANTASY_YEAR_GROUP
0,ARIDEF/ST2022,ARI,DEF/ST,17,2022,115.0,6.764706,5 - 10,Current Year
1,ATLDEF/ST2022,ATL,DEF/ST,17,2022,76.0,4.470588,Under 5,Current Year
2,BALDEF/ST2022,BAL,DEF/ST,17,2022,125.0,7.352941,5 - 10,Current Year
3,BUFDEF/ST2022,BUF,DEF/ST,17,2022,134.5,7.911765,5 - 10,Current Year
4,CARDEF/ST2022,CAR,DEF/ST,17,2022,113.0,6.647059,5 - 10,Current Year
...,...,...,...,...,...,...,...,...,...
91,SEADEF/ST2020,SEA,DEF/ST,16,2020,95.5,5.968750,5 - 10,Two Years Ago
92,SFODEF/ST2020,SFO,DEF/ST,16,2020,70.5,4.406250,Under 5,Two Years Ago
93,TAMDEF/ST2020,TAM,DEF/ST,16,2020,121.0,7.562500,5 - 10,Two Years Ago
94,TENDEF/ST2020,TEN,DEF/ST,16,2020,41.0,2.562500,Under 5,Two Years Ago
95,WASDEF/ST2020,WAS,DEF/ST,16,2020,130.0,8.125000,5 - 10,Two Years Ago

In [7]:
#######################################################################################
##                                                                                   ##
##            Combine Offense and Defense Datasets and export to .csv                ##
##                                                                                   ##
#######################################################################################

df_FANTASY_KPI_ROSTER = pd.concat([df_OFF_KPI_ROSTER, df_DEFENSE_KPI_ROSTER])

##############################################################################

# clean up the unique join for pbi consumption

df_FANTASY_KPI_ROSTER['UNIQUE_JOIN'] = df_FANTASY_KPI_ROSTER['UNIQUE_JOIN'].str.replace('*','', regex=True)
df_FANTASY_KPI_ROSTER['UNIQUE_JOIN'] = df_FANTASY_KPI_ROSTER['UNIQUE_JOIN'].str.replace('+','', regex=True)

##############################################################################

df_a = pd.read_csv(r'D:\Geoff\Analytics\Fantasy Football\Reference\NFL_ROSTER.csv')

df_a['TEAM_JOIN'] = df_a['TEAM'] + year_current

df_a = df_a.filter(['UNIQUE_JOIN','TEAM_JOIN','TEAM']).drop_duplicates()

df_FANTASY_KPI_ROSTER = pd.merge(df_FANTASY_KPI_ROSTER,df_a, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

##############################################################################
df_FANTASY_KPI_ROSTER.to_csv(r'D:\Geoff\Analytics\Fantasy Football\PBI Source Data\FANTASY_KPI_ROSTER.csv', index=False)

print('<<<<<<<<<<<<<<>>>>>>>>>>>>>>')
print('        FANTASY_KPI_ROSTER')
df_FANTASY_KPI_ROSTER.info()
df_FANTASY_KPI_ROSTER

<<<<<<<<<<<<<<>>>>>>>>>>>>>>
        FANTASY_KPI_ROSTER
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   UNIQUE_JOIN         1985 non-null   object
 1   PLAYER_NAME         1985 non-null   object
 2   PLAYER_POSITION     1985 non-null   object
 3   GAMES_PLAYED        1985 non-null   int64
 4   FANTASY_YEAR        1985 non-null   object
 5   YTD_SCORE           1985 non-null   float64
 6   WEEKLY_SCORE        1985 non-null   float64
 7   WEEKLY_SCORE_GROUP  1985 non-null   object
 8   FANTASY_YEAR_GROUP  1985 non-null   object
 9   TEAM_JOIN           1985 non-null   object
 10  TEAM                1985 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 186.1+ KB

,UNIQUE_JOIN,PLAYER_NAME,PLAYER_POSITION,GAMES_PLAYED,FANTASY_YEAR,YTD_SCORE,WEEKLY_SCORE,WEEKLY_SCORE_GROUP,FANTASY_YEAR_GROUP,TEAM_JOIN,TEAM
0,Patrick MahomesQB2022,Patrick Mahomes,QB,17,2022,398.40,23.435294,15 - 25,Current Year,KAN2022,KAN
1,Justin HerbertQB2022,Justin Herbert,QB,17,2022,254.26,14.956471,10 - 15,Current Year,LAC2022,LAC
2,Tom BradyQB2022,Tom Brady,QB,17,2022,253.66,14.921176,10 - 15,Current Year,0,0
3,Kirk CousinsQB2022,Kirk Cousins,QB,17,2022,255.58,15.034118,15 - 25,Current Year,MIN2022,MIN
4,Joe BurrowQB2022,Joe Burrow,QB,16,2022,319.70,19.981250,15 - 25,Current Year,CIN2022,CIN
...,...,...,...,...,...,...,...,...,...,...,...
1980,SEADEF/ST2020,SEA,DEF/ST,16,2020,95.50,5.968750,5 - 10,Two Years Ago,0,0
1981,SFODEF/ST2020,SFO,DEF/ST,16,2020,70.50,4.406250,Under 5,Two Years Ago,0,0
1982,TAMDEF/ST2020,TAM,DEF/ST,16,2020,121.00,7.562500,5 - 10,Two Years Ago,0,0
1983,TENDEF/ST2020,TEN,DEF/ST,16,2020,41.00,2.562500,Under 5,Two Years Ago,0,0
1984,WASDEF/ST2020,WAS,DEF/ST,16,2020,130.00,8.125000,5 - 10,Two Years Ago,0,0

In [9]:
df_FANTASY_KPI_ROSTER[df_FANTASY_KPI_ROSTER['PLAYER_NAME'].str.contains("Jameson Williams")]

,UNIQUE_JOIN,PLAYER_NAME,PLAYER_POSITION,GAMES_PLAYED,FANTASY_YEAR,YTD_SCORE,WEEKLY_SCORE,WEEKLY_SCORE_GROUP,FANTASY_YEAR_GROUP,TEAM_JOIN,TEAM
604,Jameson WilliamsWR2022,Jameson Williams,WR,6,2022,15.1,2.516667,Under 5,Current Year,DET2022,DET

In [6]:
#######################################################################################
##                                                                                   ##
##                       Create Fantasy Draft data source for PBI                    ##
##                                                                                   ##
#######################################################################################

df_FANTASY_DRAFT = pd.read_csv(r'D:\Geoff\Analytics\Fantasy Football\Reference\FANTASY_DRAFT_ATTRIBUTE.csv').fillna("N/A")

df_FANTASY_DRAFT['UNIQUE_JOIN'] = df_FANTASY_DRAFT['PLAYER_NAME'] + df_FANTASY_DRAFT['PLAYER_POSITION'] + df_FANTASY_DRAFT['FANTASY_YEAR'].astype(str)

df_FANTASY_DRAFT['FANTASY_YEAR'] = df_FANTASY_DRAFT['FANTASY_YEAR'].astype(str)

##############################################################################

## Define Fantasy Year Group

#define condition of each value
conditions = [
    (df_FANTASY_DRAFT['FANTASY_YEAR'] == year_current),
    (df_FANTASY_DRAFT['FANTASY_YEAR'] == year_prior1),
    (df_FANTASY_DRAFT['FANTASY_YEAR'] == year_prior2)
]

# Define result depending on the condition met
values = ["Current Year","Prior Year","Two Years Ago"]

# Apply Condition -> result logic as a new column in the DataFrame
df_FANTASY_DRAFT['FANTASY_YEAR_GROUP'] = np.select(conditions, values)


##############################################################################

##############################################################################

## Define Fantasy Year Group

#define condition of each value
conditions = [
    (df_FANTASY_DRAFT['KEEPER'] == "Y"),
    (df_FANTASY_DRAFT['KEEPER'] == "N")
]

# Define result depending on the condition met
values = [1,0]

# Apply Condition -> result logic as a new column in the DataFrame
df_FANTASY_DRAFT['KEEPER_NUM'] = np.select(conditions, values)


##############################################################################

##############################################################################

## Define Fantasy Year Group

#define condition of each value
conditions = [
    ((df_FANTASY_DRAFT['HAN_SHOT_FIRST_PICK'] + df_FANTASY_DRAFT['KEEPER']) == "PICKY"),
    (df_FANTASY_DRAFT['KEEPER'] == "Y"),
    (df_FANTASY_DRAFT['KEEPER'] == "N")
]

# Define result depending on the condition met
values = ["Keeper","N/A Keeper",df_FANTASY_DRAFT['HAN_SHOT_FIRST_PICK']]

# Apply Condition -> result logic as a new column in the DataFrame
df_FANTASY_DRAFT['RELEVENCE_TO_MY_PICK'] = np.select(conditions, values)


##############################################################################

##############################################################################

df_1 = df_FANTASY_KPI_ROSTER.filter(['UNIQUE_JOIN','WEEKLY_SCORE']).drop_duplicates()

df_FANTASY_DRAFT = pd.merge(df_FANTASY_DRAFT,df_1, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

##############################################################################

df_FANTASY_DRAFT['NAME_AND_POSITION'] = df_FANTASY_DRAFT['PLAYER_NAME'] + " - " + df_FANTASY_DRAFT['PLAYER_POSITION']

##############################################################################

df_FANTASY_DRAFT.to_csv(r'D:\Geoff\Analytics\Fantasy Football\PBI Source Data\FANTASY_DRAFT.csv', index=False)

print('<<<<<<<<<<<<<<>>>>>>>>>>>>>>')
print('        FANTASY_DRAFT')
df_FANTASY_DRAFT.info()
df_FANTASY_DRAFT.head(5)

<<<<<<<<<<<<<<>>>>>>>>>>>>>>
        FANTASY_DRAFT
<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PLAYER_NAME           150 non-null    object
 1   PLAYER_POSITION       150 non-null    object
 2   FANTASY_YEAR          150 non-null    object
 3   DRAFT_ROUND           150 non-null    int64
 4   HAN_SHOT_FIRST_PICK   150 non-null    object
 5   KEEPER                150 non-null    object
 6   UNIQUE_JOIN           150 non-null    object
 7   FANTASY_YEAR_GROUP    150 non-null    object
 8   KEEPER_NUM            150 non-null    int32
 9   RELEVENCE_TO_MY_PICK  150 non-null    object
 10  WEEKLY_SCORE          150 non-null    float64
 11  NAME_AND_POSITION     150 non-null    object
dtypes: float64(1), int32(1), int64(1), object(9)
memory usage: 14.6+ KB

,PLAYER_NAME,PLAYER_POSITION,FANTASY_YEAR,DRAFT_ROUND,HAN_SHOT_FIRST_PICK,KEEPER,UNIQUE_JOIN,FANTASY_YEAR_GROUP,KEEPER_NUM,RELEVENCE_TO_MY_PICK,WEEKLY_SCORE,NAME_AND_POSITION
0,Alvin Kamara,RB,2022,1,Unavailable,Y,Alvin KamaraRB2022,Current Year,1,N/A Keeper,14.646667,Alvin Kamara - RB
1,Jonathan Taylor,RB,2022,1,PRIOR 2,N,Jonathan TaylorRB2022,Current Year,0,PRIOR 2,13.854545,Jonathan Taylor - RB
2,Austin Ekeler,RB,2022,1,PRIOR 1,N,Austin EkelerRB2022,Current Year,0,PRIOR 1,22.276471,Austin Ekeler - RB
3,Dalvin Cook,RB,2022,1,PICK,N,Dalvin CookRB2022,Current Year,0,PICK,14.458824,Dalvin Cook - RB
4,Derrick Henry,RB,2022,1,POST 1,N,Derrick HenryRB2022,Current Year,0,POST 1,19.297500,Derrick Henry - RB

In [7]:
df_ROSTER = pd.read_csv(r'D:\Geoff\Analytics\Fantasy Football\Reference\NFL_ROSTER.csv')

df_ROSTER

,Player,Pos,TEAM,ROSTER_YEAR,UNIQUE_JOIN,TEAM_JOIN
0,Robbie Anderson,WR,ARI,2022,Robbie AndersonWR2022,ARI2022
1,Stephen Anderson,TE,ARI,2022,Stephen AndersonTE2022,ARI2022
2,Andre Baccellia,WR,ARI,2022,Andre BaccelliaWR2022,ARI2022
3,Budda Baker,S,ARI,2022,Budda BakerS2022,ARI2022
4,Chris Banjo,DB,ARI,2022,Chris BanjoDB2022,ARI2022
...,...,...,...,...,...,...
2314,Chris Wilcox,CB,PIT,2022,Chris WilcoxCB2022,PIT2022
2315,Rod Williams,WR,PIT,2022,Rod WilliamsWR2022,PIT2022
2316,Ahkello Witherspoon,CB,PIT,2022,Ahkello WitherspoonCB2022,PIT2022
2317,Chris Wormley,NT,PIT,2022,Chris WormleyNT2022,PIT2022
2318,Renell Wren,DT,PIT,2022,Renell WrenDT2022,PIT2022

In [8]:
df_a = pd.read_csv(r'D:\Geoff\Analytics\Fantasy Football\Reference\NFL_ROSTER.csv')

df_a['TEAM_JOIN'] = df_a['TEAM'] + year_current

df_a = df_a.filter(['UNIQUE_JOIN','TEAM_JOIN','TEAM']).drop_duplicates()

df = pd.merge(df_FANTASY_KPI_ROSTER,df_a, on='UNIQUE_JOIN',how='left').fillna(0).drop_duplicates()

df

,UNIQUE_JOIN,PLAYER_NAME,PLAYER_POSITION,GAMES_PLAYED,FANTASY_YEAR,YTD_SCORE,WEEKLY_SCORE,WEEKLY_SCORE_GROUP,FANTASY_YEAR_GROUP,TEAM_JOIN_x,TEAM_x,TEAM_JOIN_y,TEAM_y
0,Patrick MahomesQB2022,Patrick Mahomes,QB,17,2022,398.40,23.435294,15 - 25,Current Year,KAN2022,KAN,KAN2022,KAN
1,Justin HerbertQB2022,Justin Herbert,QB,17,2022,254.26,14.956471,10 - 15,Current Year,LAC2022,LAC,LAC2022,LAC
2,Tom BradyQB2022,Tom Brady,QB,17,2022,253.66,14.921176,10 - 15,Current Year,0,0,0,0
3,Kirk CousinsQB2022,Kirk Cousins,QB,17,2022,255.58,15.034118,15 - 25,Current Year,MIN2022,MIN,MIN2022,MIN
4,Joe BurrowQB2022,Joe Burrow,QB,16,2022,319.70,19.981250,15 - 25,Current Year,CIN2022,CIN,CIN2022,CIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1980,SEADEF/ST2020,SEA,DEF/ST,16,2020,95.50,5.968750,5 - 10,Two Years Ago,0,0,0,0
1981,SFODEF/ST2020,SFO,DEF/ST,16,2020,70.50,4.406250,Under 5,Two Years Ago,0,0,0,0
1982,TAMDEF/ST2020,TAM,DEF/ST,16,2020,121.00,7.562500,5 - 10,Two Years Ago,0,0,0,0
1983,TENDEF/ST2020,TEN,DEF/ST,16,2020,41.00,2.562500,Under 5,Two Years Ago,0,0,0,0
1984,WASDEF/ST2020,WAS,DEF/ST,16,2020,130.00,8.125000,5 - 10,Two Years Ago,0,0,0,0